export {default as PokemonImage} from './PokemonImage'
export {default as PokemonTypes} from './PokemonTypes'
export {default as HeaderDetails} from './HeaderDetails'
export {default as PokemonName} from './PokemonName'
export {default as PokemonOtherStats} from './PokemonOtherStats'
export {default as PokemonMainStats} from './PokemonMainStats'
